export default {
    DOUBLE_DECK: 'double_deck',
    SHUFFLE_DECK: 'shuffle_deck',
    SET_FIRST_INDEX: 'set_first_index',
    FLIP_CARD: 'flip_card',
    ADD_GOLD: 'add_gold',
    FIND_WEAPON: 'find_weapon',
    FIND_ARMOR: 'find_armor',
    FILL_INVENTORY: 'fill_inventory',
    STAB_DRAGON: 'stab_dragon',
    TAKE_DAMAGE: 'take_damage',
    TOGGLE_MODAL: 'toggle_modal',
    FADE_MATCH: 'fade_match',
    ADD_ATTEMPT: 'add_attempt',
    ADD_MATCH: 'add_match',
    UPDATE_GAME_TOTAL: 'update_game_total',
    UPDATE_GAME_STATUS: 'update_game_status',
    TOGGLE_MATCH_KEY: 'toggle_match_key',
    UPDATE_MODAL_MESSAGE: 'update_modal_message'
};